import React, { useState } from "react";
import { CVAnalysis, JobMatchResult, PageId } from "../types";
import {
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Sparkles,
  Download,
  ArrowRight,
  Loader2,
  HelpCircle,
  PieChart,
} from "lucide-react";

interface JobMatchSectionProps {
  cv: CVAnalysis | null;
  rawCvText?: string;
  initialJobDescription?: string;
  initialJobTitle?: string;
  matchResult: JobMatchResult | null;
  onMatchComplete: (result: JobMatchResult, jd: string, title: string) => void;
  onNavigate: (page: PageId) => void;
}

export const JobMatchSection: React.FC<JobMatchSectionProps> = ({
  cv,
  rawCvText,
  initialJobDescription = "",
  initialJobTitle = "",
  matchResult,
  onMatchComplete,
  onNavigate,
}) => {
  const [jobDescription, setJobDescription] = useState(initialJobDescription);
  const [jobTitle, setJobTitle] = useState(initialJobTitle || "Custom Job Description");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleRunMatch = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!cv) {
      setErrorMsg("Please upload your CV before running compatibility matching.");
      return;
    }
    if (!jobDescription.trim() || jobDescription.trim().length < 30) {
      setErrorMsg("Please provide a more detailed Job Description (at least 30 characters).");
      return;
    }

    setIsLoading(true);
    setErrorMsg(null);

    try {
      const response = await fetch("/api/match-job", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ cvData: cv, jobDescription }),
      });

      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(data.error || "Failed to compare CV and Job Description.");
      }

      const result: JobMatchResult = await response.json();
      onMatchComplete(result, jobDescription, jobTitle);
    } catch (err: any) {
      console.error(err);
      setErrorMsg(err.message || "Encountered an error evaluating match.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadReport = () => {
    if (!matchResult) return;

    const reportContent = `# JobFinder AI - Comprehensive Analysis Report
**Target Role:** ${jobTitle}
**Candidate:** ${cv?.name || "Candidate"}
**Generated on:** ${new Date().toLocaleDateString()}

---

## ${matchResult.compatibility_label}
*${matchResult.score_calculation_explanation}*

### Skills Breakdown
- **Matching Skills (${matchResult.matching_skills.length}):** ${matchResult.matching_skills.join(", ") || "None"}
- **Missing Skills (${matchResult.missing_skills.length}):** ${matchResult.missing_skills.join(", ") || "None"}
- **Partially Matching (${matchResult.partially_matching_skills.length}):** ${matchResult.partially_matching_skills.join(", ") || "None"}

### Dimensional Evaluation
- **Experience Match:** ${matchResult.experience_match_score}% - ${matchResult.experience_match_description}
- **Education Match:** ${matchResult.education_match_score}% - ${matchResult.education_match_description}
- **Project Relevance:** ${matchResult.project_relevance_score}% - ${matchResult.project_relevance_description}

### Key Strengths
${matchResult.strengths.map((s) => `- ${s}`).join("\n")}

### Identified Gaps
${matchResult.weaknesses_and_gaps.map((g) => `- ${g}`).join("\n")}

### Recommendations
${matchResult.recommendations.map((r) => `- ${r}`).join("\n")}

---
*Report generated by JobFinder AI — Powered by Google Gemini API*
`;

    const blob = new Blob([reportContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `JobFinder_Match_${(cv?.name || "Candidate").replace(/\s+/g, "_")}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto py-6 space-y-8">
      <div>
        <h2 className="text-2xl font-extrabold text-slate-900 tracking-tight">
          Job Compatibility Matching
        </h2>
        <p className="text-sm text-slate-600">
          Compare your uploaded CV against any target job description. The AI calculates multi-factor alignment, identifying matching competencies, adjacent experience, and exact skill gaps.
        </p>
      </div>

      {!cv && (
        <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-amber-900 flex items-center justify-between">
          <div className="text-sm">
            <span className="font-bold">No CV active.</span> Please upload your resume first to run compatibility matching.
          </div>
          <button
            onClick={() => onNavigate("Upload CV")}
            className="px-4 py-1.5 rounded-lg bg-amber-700 text-white font-semibold text-xs hover:bg-amber-800 transition"
          >
            Upload CV Now
          </button>
        </div>
      )}

      {/* Input Form */}
      <form onSubmit={handleRunMatch} className="bg-white p-6 rounded-xl border border-slate-200 shadow-xs space-y-4">
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
            Target Job Title / Company
          </label>
          <input
            type="text"
            value={jobTitle}
            onChange={(e) => setJobTitle(e.target.value)}
            placeholder="e.g. Senior Backend Engineer at Stripe"
            className="w-full text-sm p-2.5 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-hidden"
          />
        </div>

        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
            Job Description & Requirements
          </label>
          <textarea
            rows={7}
            value={jobDescription}
            onChange={(e) => setJobDescription(e.target.value)}
            placeholder="Paste the target job requirements, qualifications, and role responsibilities here..."
            className="w-full text-sm p-3 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-hidden font-mono"
          />
        </div>

        {errorMsg && (
          <div className="text-xs text-rose-600 bg-rose-50 border border-rose-200 p-3 rounded-lg font-medium">
            {errorMsg}
          </div>
        )}

        <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
          <div className="text-xs text-slate-400">
            {cv ? `Comparing against: ${cv.name || "Candidate"}` : "Waiting for CV upload"}
          </div>
          <button
            id="run-match-eval-btn"
            type="submit"
            disabled={isLoading || !cv}
            className="px-6 py-2.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-semibold text-sm transition flex items-center gap-2 disabled:opacity-50"
          >
            {isLoading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Evaluating Compatibility...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                Run AI Compatibility Evaluation
              </>
            )}
          </button>
        </div>
      </form>

      {/* Results Section */}
      {matchResult && (
        <div className="space-y-6 pt-2">
          {/* Overall Score Banner */}
          <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-sm space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-4">
              <div>
                <div className="text-xs font-bold uppercase tracking-wider text-blue-600">
                  Target Evaluation: {jobTitle}
                </div>
                <div className="text-3xl font-black text-slate-900 mt-1">
                  {matchResult.compatibility_label}
                </div>
              </div>

              {/* Circular Gauge / Percentage pill */}
              <div className="flex items-center gap-3">
                <div className="w-16 h-16 rounded-full bg-blue-50 border-4 border-blue-600 flex items-center justify-center font-black text-xl text-blue-700">
                  {matchResult.overall_match_percentage}%
                </div>
              </div>
            </div>

            {/* Explanation */}
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs sm:text-sm text-slate-700 leading-relaxed space-y-1">
              <div className="font-semibold text-slate-900 flex items-center gap-1.5">
                <HelpCircle className="w-4 h-4 text-blue-600" />
                Score Calculation & Arithmetic Breakdown
              </div>
              <p>{matchResult.score_calculation_explanation}</p>
            </div>
          </div>

          {/* 3 Dimensional Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-5 rounded-xl bg-white border border-slate-200 shadow-xs">
              <div className="text-xs font-bold uppercase tracking-wider text-slate-400">Experience Alignment</div>
              <div className="text-2xl font-black text-slate-900 mt-1 mb-1">
                {matchResult.experience_match_score}%
              </div>
              <p className="text-xs text-slate-600 leading-relaxed">
                {matchResult.experience_match_description}
              </p>
            </div>

            <div className="p-5 rounded-xl bg-white border border-slate-200 shadow-xs">
              <div className="text-xs font-bold uppercase tracking-wider text-slate-400">Education Alignment</div>
              <div className="text-2xl font-black text-slate-900 mt-1 mb-1">
                {matchResult.education_match_score}%
              </div>
              <p className="text-xs text-slate-600 leading-relaxed">
                {matchResult.education_match_description}
              </p>
            </div>

            <div className="p-5 rounded-xl bg-white border border-slate-200 shadow-xs">
              <div className="text-xs font-bold uppercase tracking-wider text-slate-400">Project Relevance</div>
              <div className="text-2xl font-black text-slate-900 mt-1 mb-1">
                {matchResult.project_relevance_score}%
              </div>
              <p className="text-xs text-slate-600 leading-relaxed">
                {matchResult.project_relevance_description}
              </p>
            </div>
          </div>

          {/* Skills Breakdown 3 Columns */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-5 rounded-xl bg-white border border-emerald-200 space-y-3">
              <div className="flex items-center gap-2 text-emerald-700 font-bold text-sm">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                Matching Skills ({matchResult.matching_skills.length})
              </div>
              <div className="flex flex-wrap gap-1.5">
                {matchResult.matching_skills.length > 0 ? (
                  matchResult.matching_skills.map((s, idx) => (
                    <span
                      key={idx}
                      className="px-2 py-0.5 rounded text-xs font-medium bg-emerald-50 text-emerald-800 border border-emerald-200"
                    >
                      {s}
                    </span>
                  ))
                ) : (
                  <span className="text-xs text-slate-400">None identified</span>
                )}
              </div>
            </div>

            <div className="p-5 rounded-xl bg-white border border-rose-200 space-y-3">
              <div className="flex items-center gap-2 text-rose-700 font-bold text-sm">
                <XCircle className="w-4 h-4 text-rose-600" />
                Missing Skills ({matchResult.missing_skills.length})
              </div>
              <div className="flex flex-wrap gap-1.5">
                {matchResult.missing_skills.length > 0 ? (
                  matchResult.missing_skills.map((s, idx) => (
                    <span
                      key={idx}
                      className="px-2 py-0.5 rounded text-xs font-medium bg-rose-50 text-rose-800 border border-rose-200"
                    >
                      {s}
                    </span>
                  ))
                ) : (
                  <span className="text-xs text-emerald-600 font-medium">No missing skills detected!</span>
                )}
              </div>
            </div>

            <div className="p-5 rounded-xl bg-white border border-amber-200 space-y-3">
              <div className="flex items-center gap-2 text-amber-800 font-bold text-sm">
                <AlertTriangle className="w-4 h-4 text-amber-600" />
                Adjacent / Partial ({matchResult.partially_matching_skills.length})
              </div>
              <div className="flex flex-wrap gap-1.5">
                {matchResult.partially_matching_skills.length > 0 ? (
                  matchResult.partially_matching_skills.map((s, idx) => (
                    <span
                      key={idx}
                      className="px-2 py-0.5 rounded text-xs font-medium bg-amber-50 text-amber-900 border border-amber-200"
                    >
                      {s}
                    </span>
                  ))
                ) : (
                  <span className="text-xs text-slate-400">None identified</span>
                )}
              </div>
            </div>
          </div>

          {/* Strengths and Weaknesses */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-5 rounded-xl bg-white border border-slate-200 space-y-2">
              <h4 className="text-sm font-bold text-slate-900 flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-emerald-500" />
                Key Candidate Strengths
              </h4>
              <ul className="space-y-1.5 text-xs sm:text-sm text-slate-600">
                {matchResult.strengths.map((st, idx) => (
                  <li key={idx} className="flex items-start gap-1.5">
                    <span className="text-emerald-600 font-bold">✓</span>
                    <span>{st}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-5 rounded-xl bg-white border border-slate-200 space-y-2">
              <h4 className="text-sm font-bold text-slate-900 flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-rose-500" />
                Identified Gaps & Weaknesses
              </h4>
              <ul className="space-y-1.5 text-xs sm:text-sm text-slate-600">
                {matchResult.weaknesses_and_gaps.map((wg, idx) => (
                  <li key={idx} className="flex items-start gap-1.5">
                    <span className="text-rose-500 font-bold">!</span>
                    <span>{wg}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Recommendations */}
          <div className="p-5 rounded-xl bg-white border border-slate-200 space-y-2">
            <h4 className="text-sm font-bold text-slate-900">Recommended Action Items</h4>
            <div className="space-y-1.5 text-xs sm:text-sm text-slate-600">
              {matchResult.recommendations.map((rec, idx) => (
                <div key={idx} className="flex items-start gap-2">
                  <span className="text-blue-600 font-bold">💡</span>
                  <span>{rec}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-wrap items-center justify-between gap-3 pt-4 border-t border-slate-200">
            <button
              onClick={handleDownloadReport}
              className="px-5 py-2.5 rounded-lg bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 font-semibold text-sm transition inline-flex items-center gap-2"
            >
              <Download className="w-4 h-4 text-slate-500" />
              Download Match Report (Markdown)
            </button>

            <button
              id="get-tailored-improvements-btn"
              onClick={() => onNavigate("CV Improvement")}
              className="px-6 py-2.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-semibold text-sm transition inline-flex items-center gap-2"
            >
              Get Tailored CV Improvements for this Job
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
