"""
Utility functions, session state managers, and formatting helpers for JobFinder AI.
"""

import json
from typing import Dict, Any, Optional

try:
    import streamlit as st
    HAS_STREAMLIT = True
except ImportError:
    HAS_STREAMLIT = False


def init_session_state():
    """Ensure all required Streamlit session state keys exist with defaults."""
    if not HAS_STREAMLIT:
        return

    defaults = {
        "nav_page": "Home",
        "sidebar_nav_selection": "Home",
        "uploaded_cv": None,
        "extracted_text": None,
        "cv_raw_text": None,
        "cv_file_name": None,
        "cv_format_name": None,
        "cv_profile": None,
        "cv_analysis": None,
        "target_job_description": "",
        "target_job_title": "",
        "selected_job": None,
        "job_profile": None,
        "match_result": None,
        "job_match_result": None,
        "cv_improvement_result": None,
        "user_api_key_override": "",
        "use_cv_skills": False,
        "filter_title": "",
        "filter_skills": "",
        "filter_location": "",
        "filter_work_type": "All",
        "filter_exp_level": "All",
        "job_match_jd_input": "",
    }

    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val


def set_nav_page(page_name: str):
    """Safely navigate to another page in Streamlit, keeping sidebar in lockstep."""
    if HAS_STREAMLIT:
        st.session_state["nav_page"] = page_name
        


def clear_cv_state():
    """Clear parsed CV and downstream results."""
    if not HAS_STREAMLIT:
        return
    st.session_state["uploaded_cv"] = None
    st.session_state["extracted_text"] = None
    st.session_state["cv_raw_text"] = None
    st.session_state["cv_file_name"] = None
    st.session_state["cv_format_name"] = None
    st.session_state["cv_profile"] = None
    st.session_state["cv_analysis"] = None
    st.session_state["job_profile"] = None
    st.session_state["match_result"] = None
    st.session_state["job_match_result"] = None
    st.session_state["cv_improvement_result"] = None


def export_report_markdown(
    cv_data: Optional[Dict[str, Any]],
    match_result: Optional[Dict[str, Any]],
    job_title: str = "Target Position",
) -> str:
    """Generate a clean Markdown summary report for export/download."""
    md = [
        f"# JobFinder AI - Comprehensive Analysis Report",
        f"**Target Role:** {job_title}",
        f"**Candidate:** {cv_data.get('name', 'Candidate') if cv_data else 'N/A'}",
        "",
        "---",
        "",
    ]

    if match_result:
        md.append(f"## {match_result.get('compatibility_label', 'AI Compatibility Score')}")
        md.append(f"*{match_result.get('score_calculation_explanation', '')}*")
        md.append("")
        md.append("### Skills Breakdown")
        matching = match_result.get("matching_skills", [])
        missing = match_result.get("missing_skills", [])
        partial = match_result.get("partially_matching_skills", [])

        md.append(f"- **Matching Skills ({len(matching)}):** {', '.join(matching) or 'None'}")
        md.append(f"- **Missing Skills ({len(missing)}):** {', '.join(missing) or 'None'}")
        md.append(f"- **Partially Matching ({len(partial)}):** {', '.join(partial) or 'None'}")
        md.append("")

        md.append("### Key Strengths")
        for s in match_result.get("strengths", []):
            md.append(f"- {s}")
        md.append("")

        md.append("### Identified Gaps")
        for g in match_result.get("weaknesses_and_gaps", []):
            md.append(f"- {g}")
        md.append("")

        md.append("### Recommendations")
        for r in match_result.get("recommendations", []):
            md.append(f"- {r}")
        md.append("")

    if cv_data:
        md.append("---")
        md.append("## Parsed CV Profile")
        md.append(f"**Professional Summary:** {cv_data.get('professional_summary', '')}")
        md.append("")
        md.append(f"**Years of Experience:** {cv_data.get('years_of_experience', 'Not specified')}")
        md.append("")
        md.append(f"**Technical Skills:** {', '.join(cv_data.get('technical_skills', []))}")
        md.append("")
        md.append(f"**Soft Skills:** {', '.join(cv_data.get('soft_skills', []))}")
        md.append("")

    md.append("---")
    md.append("*Generated by JobFinder AI - Powered by Google Gemini API*")
    return "\n".join(md)


def load_custom_css() -> str:
    """Returns custom CSS for an ultra-clean, modern hackathon UI."""
    return """
    <style>
    /* Global styling */
    .main {
        background-color: #f8fafc;
        color: #0f172a;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    }
    
    /* Header Card */
    .hero-container {
        background: #ffffff;
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        padding: 32px 28px;
        margin-bottom: 24px;
        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.05);
    }
    
    .hero-title {
        font-size: 2.25rem;
        font-weight: 700;
        color: #0f172a;
        margin-bottom: 8px;
        letter-spacing: -0.025em;
    }
    
    .hero-subtitle {
        font-size: 1.125rem;
        color: #475569;
        line-height: 1.6;
        max-width: 75ch;
    }
    
    /* Feature cards */
    .metric-card {
        background: #ffffff;
        border: 1px solid #e2e8f0;
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 16px;
        transition: transform 0.15s ease, box-shadow 0.15s ease;
    }
    
    .metric-card:hover {
        border-color: #cbd5e1;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.07);
    }

    .pill-tag {
        display: inline-block;
        padding: 4px 10px;
        border-radius: 9999px;
        font-size: 0.8125rem;
        font-weight: 500;
        white-space: nowrap;
        margin-right: 6px;
        margin-bottom: 6px;
    }

    .pill-green {
        background-color: #ecfdf5;
        color: #065f46;
        border: 1px solid #a7f3d0;
    }

    .pill-blue {
        background-color: #eff6ff;
        color: #1e40af;
        border: 1px solid #bfdbfe;
    }

    .pill-amber {
        background-color: #fffbeb;
        color: #92400e;
        border: 1px solid #fde68a;
    }

    .pill-rose {
        background-color: #fff1f2;
        color: #9f1239;
        border: 1px solid #fecdd3;
    }

    .pill-slate {
        background-color: #f1f5f9;
        color: #334155;
        border: 1px solid #e2e8f0;
    }

    /* Score display */
    .score-badge-large {
        font-size: 2.75rem;
        font-weight: 800;
        color: #2563eb;
        line-height: 1;
        margin-bottom: 4px;
    }
    
    .score-label {
        font-size: 0.9375rem;
        font-weight: 600;
        color: #334155;
    }
    </style>
    """
